### ISSUE TITLE
v1.4.6 is missing

### ISSUE THREAD

**Issue by YunCaiCaoYuan** [ferd/cth_readable#27]
this comes from my console：

===> Verifying dependencies...
escript: exception error: no match of right hand side value
                 {error,
                     {rebar_app_utils,
                         {missing_package,<<"cth_readable">>,<<"1.4.6">>}}}
  in function  erl_eval:expr/5 (erl_eval.erl, line 453)
  in call from escript:eval_exprs/5 (escript.erl, line 872)
  in call from erl_eval:local_func/6 (erl_eval.erl, line 567)
  in call from escript:interpret/4 (escript.erl, line 788)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 (init.erl, line 1115)
  in call from init:do_boot/3 (init.erl, line 823)

**Comment by ferd** [comment]
It's there though: https://hex.pm/packages/cth_readable/1.4.6 and even [rebar3 depends on it](https://github.com/erlang/rebar3/blob/master/rebar.lock#L5).
