### ISSUE TITLE
cth_readable_failonly consumes large amount of memory with lot's of log statements

### ISSUE THREAD

**Issue by TheGeorge** [ferd/cth_readable#33]
We ran into an issue with `cth_readable` where the gen_server in `cth_readable_failonly` consumes large quantities of memory, due to it buffering all IO in the gen_server state.

Would a PR be considered, where we make this configurable, and only buffer the last X events for printout, with the default being the current behavior?

**Comment by ferd** [comment]
Yeah I don't think there would be a problem with that. Would probably need to count how many lines are dropped and show that as well. The configuration should be done through the usual ct hook configuration mechanism (at their declaration site in the config) for cth_readable to remain usable outside of rebar3 as well.
