### ISSUE TITLE
Add support for `cthr:pal/5`

### ISSUE THREAD

**Issue by ashleyjlive** [ferd/cth_readable#36]
### Problem
During testing it was discovered that calls to `ct:pal/5` were failing with undef errors when the parse_transform `cth_readable_transform` was used. This is because `cthr:pal/5` does not exist.
### Solution
Implement `cthr:pal/5` (which has support for opts).

Please see commit https://github.com/ashleyjlive/cth_readable/commit/46c0a804345d9637972852bfb389d027931cc686

**Comment by ferd** [comment]
Yeah that sounds fine. If you want to open a PR I can review and merge.

**Comment by ashleyjlive** [comment]
Pull request merged.
https://github.com/ferd/cth_readable/pull/37
